<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <title>Tabaka</title>
    <meta name="description" content="Admintres is a Dashboard & Admin Site Responsive Template by hencework."/>
    <meta name="keywords"
          content="admin, admin dashboard, admin template, cms, crm, Admintres Admin, Admintresadmin, premium admin templates, responsive admin, sass, panel, software, ui, visualization, web app, application"/>
    <meta name="author" content="hencework"/>

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?= $this->url->get('') ?>favicon.ico">
    <link rel="icon" href="<?= $this->url->get('') ?>favicon.ico" type="image/x-icon">

    <!-- Data table CSS -->
    <link href="<?= $this->url->get('') ?>vendors/bower_components/datatables/media/css/jquery.dataTables.min.css"
          rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('') ?>vendors/bower_components/datatables.net-responsive/css/responsive.dataTables.min.css"
          rel="stylesheet" type="text/css"/>

    <!-- Custom CSS -->
    <link href="<?= $this->url->get('') ?>dist/css/style.css" rel="stylesheet" type="text/css">
    <script src="<?= $this->url->get('') ?>vendors/bower_components/jquery/dist/jquery.min.js"></script>
    <style>
        .map {
            height: 500px;
        }
    </style>
</head>
<?php if ($this->session->get('id')): ?>
<body>
<!--Preloader-->
<div class="preloader-it">
    <div class="la-anim-1"></div>
</div>
<!--/Preloader-->
<div class="wrapper theme-2-active navbar-top-light horizontal-nav">
    <!-- Top Menu Items -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="nav-wrap">
            <div class="mobile-only-brand pull-left">
                <div class="nav-header pull-left">
                    <div class="logo-wrap">
                        <a href="<?= $this->url->get('') ?>">
                            <img class="brand-img" src="<?= $this->url->get('') ?>img/logo.png" alt="brand"/>
                            <span class="brand-text"><img src="<?= $this->url->get('') ?>img/brand.png"
                                                          alt="brand"/></span>
                        </a>
                    </div>
                </div>
                <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left"
                   href="javascript:void(0);"><i class="ti-align-left"></i></a>
                <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view"
                   href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
                <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i
                            class="ti-more"></i></a>
                <form id="search_form" role="search" class="top-nav-search collapse pull-left">
                    <div class="input-group">
                        <input type="text" name="example-input1-group2" class="form-control" placeholder="Search">
                        <span class="input-group-btn">
							<button type="button" class="btn  btn-default" data-target="#search_form"
                                    data-toggle="collapse" aria-label="Close" aria-expanded="true"><i
                                        class="zmdi zmdi-search"></i></button>
							</span>
                    </div>
                </form>
            </div>
            <div id="mobile_only_nav" class="mobile-only-nav pull-right">
                <ul class="nav navbar-right top-nav pull-right">
                    <li class="dropdown auth-drp">
                        <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown"><img
                                    src="<?= $this->url->get('') ?>img/user1.png" alt="user_auth"
                                    class="user-auth-img img-circle"/><span class="user-online-status"></span></a>
                        <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX"
                            data-dropdown-out="flipOutX">
                            <li class="divider"></li>
                            <li>
                                <a href="<?= $this->url->get('session/logout') ?>"><i class="zmdi zmdi-power"></i><span>Log Out</span></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- /Top Menu Items -->

    <!-- Left Sidebar Menu -->
    <div class="fixed-sidebar-left">
        <ul class="nav navbar-nav side-nav nicescroll-bar">
            <li class="navigation-header">
                <span>Main</span>
                <hr/>
            </li>
            <li>
                <a href="<?= $this->url->get('') ?>">
                    <div class="pull-left"><i class="ti-dashboard mr-20"></i><span class="right-nav-text">home</span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li>
                <a href="<?= $this->url->get('lokasi') ?>">
                    <div class="pull-left"><i class="ti-marker-alt mr-20"></i><span
                                class="right-nav-text">data master lokasi</span></div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li>
                <a href="<?= $this->url->get('index/pengguna') ?>">
                    <div class="pull-left"><i class="ti-user mr-20"></i><span
                                class="right-nav-text">data pengguna</span></div>
                    <div class="clearfix"></div>
                </a>
            </li>
        </ul>
    </div>
    <!-- /Left Sidebar Menu -->

    <!-- Main Content -->
    <div class="page-wrapper">
        <div class="container pt-30">
            <?php $this->flashSession->output() ?>
            <?= $this->getContent('') ?>
        </div>

        <!-- Footer -->
        <footer class="footer pl-30 pr-30">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <p>2018 &copy; PMB</p>
                    </div>
                    <div class="col-sm-6 text-right">
                        <p>Follow Us</p>
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-google-plus"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /Footer -->

    </div>
    <!-- /Main Content -->

</div>
<!-- /#wrapper -->

<!-- JavaScript -->
<?php else: ?>
    <?= $this->getContent('') ?>
<?php endif; ?>
<!-- jQuery -->

<!-- Bootstrap Core JavaScript -->
<script src="<?= $this->url->get('') ?>vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Data table JavaScript -->
<script src="<?= $this->url->get('') ?>vendors/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?= $this->url->get('') ?>vendors/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?= $this->url->get('') ?>vendors/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?= $this->url->get('') ?>dist/js/responsive-datatable-data.js"></script>

<!-- Slimscroll JavaScript -->
<script src="<?= $this->url->get('') ?>dist/js/jquery.slimscroll.js"></script>

<!-- Owl JavaScript -->
<script src="<?= $this->url->get('') ?>vendors/bower_components/owl.carousel/dist/owl.carousel.min.js"></script>

<!-- Switchery JavaScript -->
<script src="<?= $this->url->get('') ?>vendors/bower_components/switchery/dist/switchery.min.js"></script>

<!-- Fancy Dropdown JS -->
<script src="<?= $this->url->get('') ?>dist/js/dropdown-bootstrap-extended.js"></script>

<!-- Init JavaScript -->
<script src="<?= $this->url->get('') ?>dist/js/init.js"></script>


</body>

</html>
